name: Execute test.sh on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
            node-version: 16

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Execute SH file
        run: sh ../project/tests.sh